---
title: "Summary statistics full data"
author: "Luna Zhang"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
   # theme: cosmo
   # highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F,
                      root.dir = "e:/500390_OAD/output/modeling/" )
```

```{r, include=F}
# Luna Zhang Feb 28 2022

# library(data.table)
suppressWarnings({
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(ggpubr)
})

# source("utils.R")

fileDir <- "e:/500390_OAD/output/" # "z:/Luna/500390_OAD/explore/"
rawfileDir <- "z:/Luna/500390_OAD/OAD Dairy Data/"
outputDir <- "e:/500390_OAD/output/modeling/" # copy to "z:/Luna/500390_OAD/output/" later

if(!exists(outputDir)) {
  dir.create(outputDir)
}
# stop()
```

```{r, include = F}
full_df <- readRDS(paste0(fileDir,
                          "production_survival_noYoungAnimal_ebv_beforeParity5.RData"))
```


```{r, eval = F}
names(full_df)
 
#  [1] "AnimalDurableCode"             "DaysFromBirthToParturition"   
#  [3] "DaysFromParturitionToHerdTest" "InducedParturitionFlag"       
#  [5] "Volume_ml"                     "FatVolume_ml"                 
#  [7] "ProteinVolume_ml"              "AgeParity"                    
#  [9] "HerdDurableKey"                "DairyYear"                    
# [11] "Season"                        "EventDate"                    
# [13] "AgeParityGroup"                "RegimeType"                   
# [15] "event_date"                    "herd_milk_type"               
# [17] "transition_year"               "s12"                          
# [19] "s23"                           "s34"                          
# [21] "s45"                           "EBV_BodyConditionScore"       
# [23] "EBV_Fertility_CR42"            "EBV_Fertility_CSD0"           
# [25] "EBV_Fertility_CSD123"          "EBV_Fertility_PM123"          
# [27] "EBV_FunctionalSurvival"        "EBV_IndirectSurvival"         
# [29] "EBV_SomaticCellScore"          "EBV_Survival"                 
# [31] "EBV_TOP_AdaptabilityToMilking" "EBV_TOP_Capacity"             
# [33] "EBV_TOP_DairyConformation"     "EBV_TOP_ForeUdder"            
# [35] "EBV_TOP_FrontTeat"             "EBV_TOP_Legs"                 
# [37] "EBV_TOP_MilkingSpeed"          "EBV_TOP_OverallOpinion"       
# [39] "EBV_TOP_RearTeat"              "EBV_TOP_RearUdder"            
# [41] "EBV_TOP_RumpAngle"             "EBV_TOP_RumpWidth"            
# [43] "EBV_TOP_ShedTemperament"       "EBV_TOP_Stature"              
# [45] "EBV_TOP_TeatLength"            "EBV_TOP_UdderOverall"         
# [47] "EBV_TOP_UdderSupport"          "EBV_TotalFat"                 
# [49] "EBV_TotalProtein"              "EBV_TotalVolume"              
# [51] "transition_parity"             "new_milk_type"                
```

# Statistics by milking type and herd

Herd size distribution in each milking type

```{r, cache = T}
df_plot <- group_by(full_df, new_milk_type, HerdDurableKey) %>% 
  tally() 

df_plot %>% ungroup() %>%
  group_by(new_milk_type) %>% 
  summarise(count = n(),
            min = min(n), median = median(n), mean = mean(n), max = max(n)) %>% 
  knitr::kable(digits = 2, caption = "Mean herd sizes in each milking type")
  

df_plot %>% 
  gghistogram(x = "n", binwidth = 5, add = "mean", fill = "new_milk_type",
              title = "Herd size distribution in each milking type"
              ) %>% 
  facet("new_milk_type", scales = "free") %>% 
  ggpar(legend = "none")

```

# survival vs milking type

*Animals with missing survival are removed.*

```{r, cache = T}
sur_milk_type <- lapply(2:5, function(i) {
  out <- full_df %>% filter(AgeParity==i) %>% 
    filter(across(paste0("s", i-1, i), ~.%in%c(T, F))) %>% 
    group_by(new_milk_type, across(paste0("s", i-1, i))) %>% 
    tally() %>% 
    mutate(prp = round(n/sum(n), digits = 2),
           survival = paste0("s", i-1, i))
  names(out)[2] <- "survived"
  
  return(out)
})
sur_milk_type <- do.call(rbind, sur_milk_type)
knitr::kable(sur_milk_type)
write.csv(sur_milk_type, paste0(outputDir, "survival_in_milk_type.csv"),
          quote = F, row.names = F)
```

# EBV within each survival and milking type

```{r, results='asis'}

ebv_sur_milk <- lapply(2:5, function(i) {
  out <- full_df %>% filter(AgeParity==i) %>% 
    filter(across(paste0("s", i-1, i), ~.%in%c(T, F))) %>% 
    select(new_milk_type, starts_with("s"), starts_with("EBV")) %>% 
    group_by(new_milk_type, across(paste0("s", i-1, i))) %>% 
    summarise(across(starts_with("EBV"), ~mean(.), na.rm = T)) %>% 
    mutate(survival = paste0("s", i-1, i))
  names(out)[2] <- "survived"
  
  return(out)
})
ebv_sur_milk <- do.call(rbind, ebv_sur_milk)

longer <- ebv_sur_milk %>% 
  pivot_longer(starts_with("EBV"), "trait", values_to = "mean_EBV") %>% 
  arrange(survival, new_milk_type, trait, survived) %>% 
  pivot_wider(names_from = survived, values_from = mean_EBV, 
              names_prefix = "survived_") 

longer$diff <- longer$survived_FALSE-longer$survived_TRUE
knitr::kable(longer, digits = 3)
write.csv(longer, paste0(outputDir, "EBV_in_survival_milk_type.csv"),
          quote = F, row.names = F)

```

# EBV distribution within herd_milk_type


```{r, eval = F}
rmarkdown::render(output_dir = outputDir, 
                  input = rstudioapi::getSourceEditorContext()$path)
```
